import type {
  LecturePlan,
  LectureProfile,
  LectureScript,
  OptionSchema,
  Project,
  SlideSpecification,
  SourceAnalysis,
} from "../types";
import type { VideoIntroItem } from "../types";

const loc = (title: string, line: number) => ({
  section_id: title,
  section_title: title,
  line,
  page: 1,
});

export const OPTION_SCHEMA: OptionSchema = {
  basic: [
    "audience_level",
    "duration_minutes",
    "difficulty",
    "lecture_type",
    "explanation_depth",
    "source_policy",
  ],
  advanced: [
    "slide_density",
    "visual_level",
    "example_level",
    "practice_level",
    "code_level",
    "quiz_mode",
    "lecture_tone",
    "speaker_notes",
    "video_intro",
  ],
  duration_minutes: { min: 5, max: 240, recommended: [20, 40, 60, 90] },
  values: {
    preset: ["concept_focused", "practice_focused", "balanced", "exam_preparation"],
    audience_level: [
      "general",
      "high_school",
      "university_beginner",
      "university_intermediate",
      "university_advanced",
      "graduate",
      "professional",
    ],
    difficulty: ["introductory", "beginner", "intermediate", "advanced"],
    lecture_type: ["theory", "example_based", "practice", "mixed", "exam_preparation"],
    explanation_depth: ["concise", "standard", "detailed"],
    source_policy: ["source_only", "source_first", "expanded"],
    slide_density: ["concise", "normal", "detailed"],
    visual_level: ["low", "medium", "high"],
    example_level: ["none", "low", "medium", "high"],
    practice_level: ["none", "simple", "guided", "full"],
    code_level: ["none", "snippet", "executable"],
    quiz_mode: ["none", "checkpoint", "final", "both"],
    lecture_tone: ["academic", "professional", "conversational"],
    speaker_notes: ["none", "concise", "full"],
    video_intro: ["none", "include"],
  },
};

export const SAMPLE_INTROS: VideoIntroItem[] = [
  { filename: "school-intro.mp4", name: "school-intro", size_bytes: 2_400_000 },
  { filename: "department-open.mp4", name: "department-open", size_bytes: 1_800_000 },
];

export const SAMPLE_ANALYSIS: SourceAnalysis = {
  source_id: "preview-source",
  title: "AIoT와 MQTT 입문",
  summary:
    "사물인터넷에 인공지능을 결합한 AIoT의 흐름과, 기기 사이 메시지를 전달하는 MQTT의 기본 역할을 다루는 샘플 자료입니다.",
  main_topics: [
    {
      title: "AIoT의 구성",
      summary: "센서, 네트워크, 클라우드에서 학습과 추론이 어떻게 이어지는지 정리합니다.",
      section_ids: ["s1"],
      key_concepts: ["AIoT", "센서"],
    },
    {
      title: "MQTT 메시지",
      summary: "Publish와 Subscribe로 주소와 메시지를 주고받는 방식을 설명합니다.",
      section_ids: ["s2"],
      key_concepts: ["MQTT", "토픽"],
    },
  ],
  concepts: [
    {
      name: "AIoT",
      aliases: ["Artificial Intelligence of Things"],
      description: "사물인터넷에 인공지능을 결합한 체계입니다.",
      importance: 5,
      prerequisite: [],
      source_location: loc("AIoT의 구성", 4),
      category: "definition",
      mention_count: 6,
    },
    {
      name: "MQTT",
      aliases: [],
      description: "가벼운 발행과 구독 방식으로 기기 사이 메시지를 전달합니다.",
      importance: 5,
      prerequisite: ["AIoT"],
      source_location: loc("MQTT 메시지", 12),
      category: "architecture",
      mention_count: 8,
    },
    {
      name: "토픽",
      aliases: ["topic"],
      description: "메시지를 분류하는 주소입니다.",
      importance: 4,
      prerequisite: ["MQTT"],
      source_location: loc("MQTT 메시지", 18),
      category: "definition",
      mention_count: 4,
    },
  ],
  definitions: [
    {
      term: "AIoT",
      definition: "사물인터넷에 인공지능을 결합한 체계",
      source_location: loc("AIoT의 구성", 4),
    },
  ],
  examples: [
    {
      kind: "example",
      text: "온실 센서가 습도 값을 올리면 서버가 환기 장치를 조절합니다.",
      related_concepts: ["AIoT", "MQTT"],
    },
  ],
  important_points: [
    { text: "MQTT는 확인 없는 전달을 쓰면 빠르지만 유실될 수 있습니다.", reason: "운영 주의" },
  ],
  scope_notes: [
    {
      text: "이 강의는 브로커 설치와 보안 설정은 다루지 않습니다.",
      source_location: loc("범위", 2),
    },
  ],
  sections: [
    { id: "s1", title: "AIoT의 구성", level: 1 },
    { id: "s2", title: "MQTT 메시지", level: 1 },
  ],
  estimated_complexity: { level: "beginner", score: 2 },
  warnings: [],
};

export function sampleProfile(projectId: string, now: string): LectureProfile {
  return {
    id: "preview-profile",
    project_id: projectId,
    audience_level: "university_beginner",
    duration_minutes: 20,
    difficulty: "introductory",
    lecture_type: "theory",
    explanation_depth: "standard",
    source_policy: "source_first",
    slide_density: "normal",
    visual_level: "high",
    example_level: "medium",
    practice_level: "none",
    code_level: "none",
    quiz_mode: "none",
    lecture_tone: "academic",
    speaker_notes: "concise",
    video_intro: "none",
    video_intro_file: null,
    inferred_fields: [
      "slide_density",
      "visual_level",
      "example_level",
      "practice_level",
      "code_level",
      "quiz_mode",
      "lecture_tone",
      "speaker_notes",
      "video_intro",
    ],
    created_at: now,
    updated_at: now,
  };
}

export function samplePlan(projectId: string, now: string): LecturePlan {
  return {
    id: "preview-plan",
    project_id: projectId,
    title: "AIoT와 MQTT 입문",
    audience: "university_beginner",
    duration_minutes: 20,
    difficulty: "introductory",
    lecture_type: "theory",
    explanation_depth: "standard",
    source_policy: "source_first",
    learning_objectives: [
      "AIoT가 센서, 네트워크, 클라우드로 이어지는 흐름을 말할 수 있다.",
      "MQTT의 발행과 구독이 토픽으로 메시지를 나누는 이유를 설명할 수 있다.",
    ],
    estimated_slide_count: 6,
    sections: [
      {
        id: "sec-intro",
        order: 1,
        title: "오늘의 길잡이",
        purpose: "강의 범위와 목표를 먼저 맞춥니다.",
        kind: "intro",
        duration_minutes: 2,
        importance: 3,
        concepts: ["AIoT"],
        estimated_slides: 1,
        teaching_notes: ["제목과 학습 목표만 보여 줍니다."],
      },
      {
        id: "sec-concept",
        order: 2,
        title: "AIoT의 구성",
        purpose: "센서에서 추론까지 한 줄로 잇습니다.",
        kind: "concept",
        duration_minutes: 8,
        importance: 5,
        concepts: ["AIoT", "센서"],
        estimated_slides: 2,
        teaching_notes: ["정의와 구성 요소를 나눕니다."],
      },
      {
        id: "sec-mqtt",
        order: 3,
        title: "MQTT 메시지",
        purpose: "토픽으로 주소를 나누는 이유를 설명합니다.",
        kind: "concept",
        duration_minutes: 8,
        importance: 5,
        concepts: ["MQTT", "토픽"],
        estimated_slides: 2,
        teaching_notes: ["발행과 구독을 화면에 나란히 둡니다."],
      },
      {
        id: "sec-summary",
        order: 4,
        title: "정리",
        purpose: "오늘 배운 말을 다시 모읍니다.",
        kind: "summary",
        duration_minutes: 2,
        importance: 3,
        concepts: ["AIoT", "MQTT"],
        estimated_slides: 1,
        teaching_notes: ["새 사실은 넣지 않습니다."],
      },
    ],
    metrics: {
      section_count: 4,
      slide_count: 6,
      concept_count: 3,
      definition_count: 2,
      example_count: 1,
      practice_activity_count: 0,
      practice_step_count: 0,
      code_count: 0,
      quiz_question_count: 0,
      explanation_minutes: 18,
      practice_minutes: 0,
      minutes_by_kind: { intro: 2, concept: 16, summary: 2 },
    },
    warnings: ["이 화면의 내용과 대본은 디자인 확인용 샘플입니다."],
    generated_at: now,
  };
}

export function sampleSlides(projectId: string, now: string): SlideSpecification {
  return {
    lecture_id: "preview-plan",
    project_id: projectId,
    title: "AIoT와 MQTT 입문",
    duration_minutes: 20,
    slide_count: 6,
    plan_estimated_slide_count: 6,
    slides: [
      {
        slide_number: 1,
        section_id: "sec-intro",
        section_title: "오늘의 길잡이",
        title: "AIoT와 MQTT 입문",
        slide_type: "title",
        learning_purpose: "오늘 강의의 범위와 목표를 확인한다.",
        key_message: "센서에서 추론까지, 메시지를 나누어 전달합니다.",
        message_from_source: false,
        key_points: ["AIoT의 흐름", "MQTT의 역할"],
        source_reference: loc("AIoT의 구성", 1),
        visual_instruction: "제목과 두 목표를 가운데 둡니다.",
        presenter_instruction: "오늘 배울 두 말을 먼저 읽습니다.",
        estimated_explanation_time: 120,
        concepts: ["AIoT"],
        content_origin: "structural",
      },
      {
        slide_number: 2,
        section_id: "sec-concept",
        section_title: "AIoT의 구성",
        title: "용어 정의: AIoT",
        slide_type: "definition",
        learning_purpose: "AIoT가 무엇인지 한 문장으로 말한다.",
        key_message: "AIoT는 사물인터넷에 인공지능을 결합한 체계입니다.",
        message_from_source: true,
        key_points: ["사물인터넷", "인공지능", "결합"],
        source_reference: loc("AIoT의 구성", 4),
        visual_instruction: "용어와 한 줄 정의를 크게 둡니다.",
        presenter_instruction: "정의를 천천히 읽고 구성을 예고합니다.",
        estimated_explanation_time: 240,
        concepts: ["AIoT"],
        content_origin: "source",
      },
      {
        slide_number: 3,
        section_id: "sec-concept",
        section_title: "AIoT의 구성",
        title: "센서에서 클라우드까지",
        slide_type: "architecture",
        learning_purpose: "측정, 전달, 학습이 이어지는 순서를 본다.",
        key_message: "센서가 값을 보내고 클라우드에서 학습과 추론이 이어집니다.",
        message_from_source: true,
        key_points: ["센서", "네트워크", "클라우드"],
        source_reference: loc("AIoT의 구성", 8),
        visual_instruction: "왼쪽에서 오른쪽으로 흐르는 세 상자를 그립니다.",
        presenter_instruction: "상자를 하나씩 가리키며 순서를 말합니다.",
        estimated_explanation_time: 240,
        concepts: ["AIoT", "센서"],
        content_origin: "source",
      },
      {
        slide_number: 4,
        section_id: "sec-mqtt",
        section_title: "MQTT 메시지",
        title: "용어 정의: MQTT",
        slide_type: "definition",
        learning_purpose: "MQTT가 메시지를 나누어 전달하는 이유를 말한다.",
        key_message: "MQTT는 발행과 구독으로 기기 사이 메시지를 전달합니다.",
        message_from_source: true,
        key_points: ["발행", "구독", "가벼운 전달"],
        source_reference: loc("MQTT 메시지", 12),
        visual_instruction: "발행과 구독을 양쪽 열로 나눕니다.",
        presenter_instruction: "두 역할을 번갈아 읽습니다.",
        estimated_explanation_time: 240,
        concepts: ["MQTT"],
        content_origin: "source",
      },
      {
        slide_number: 5,
        section_id: "sec-mqtt",
        section_title: "MQTT 메시지",
        title: "토픽은 주소입니다",
        slide_type: "concept",
        learning_purpose: "토픽이 메시지를 분류하는 주소임을 확인한다.",
        key_message: "토픽은 메시지를 분류하는 주소입니다.",
        message_from_source: true,
        key_points: ["주소", "분류", "구독 대상"],
        source_reference: loc("MQTT 메시지", 18),
        visual_instruction: "토픽 문자열 하나를 크게 보여 줍니다.",
        presenter_instruction: "주소라는 말만 남기고 짧게 설명합니다.",
        estimated_explanation_time: 240,
        concepts: ["토픽"],
        content_origin: "source",
      },
      {
        slide_number: 6,
        section_id: "sec-summary",
        section_title: "정리",
        title: "오늘 배운 말",
        slide_type: "summary",
        learning_purpose: "AIoT와 MQTT를 한 번씩 다시 말한다.",
        key_message: "측정한 값은 메시지로 나뉘어 학습과 추론으로 이어집니다.",
        message_from_source: false,
        key_points: ["AIoT 흐름", "MQTT 토픽"],
        source_reference: null,
        visual_instruction: "두 문장을 목록으로 둡니다.",
        presenter_instruction: "새 사실은 더하지 않고 두 문장만 읽습니다.",
        estimated_explanation_time: 120,
        concepts: ["AIoT", "MQTT"],
        content_origin: "structural",
      },
    ],
    warnings: [],
    generated_at: now,
  };
}

export function sampleScripts(projectId: string): LectureScript {
  const slides = [
    {
      slide_number: 1,
      title: "AIoT와 MQTT 입문",
      slide_type: "title",
      estimated_seconds: 120,
      spoken_seconds: 18,
      text: "오늘은 사물인터넷에 인공지능을 더한 AIoT와, 기기 사이 메시지를 나누는 MQTT를 함께 살펴보겠습니다.",
      source: "preview",
    },
    {
      slide_number: 2,
      title: "용어 정의: AIoT",
      slide_type: "definition",
      estimated_seconds: 240,
      spoken_seconds: 28,
      text: "AIoT는 사물인터넷에 인공지능을 결합한 체계입니다. 센서가 값을 모으고, 그 값이 학습과 추론으로 이어집니다.",
      source: "preview",
    },
    {
      slide_number: 3,
      title: "센서에서 클라우드까지",
      slide_type: "architecture",
      estimated_seconds: 240,
      spoken_seconds: 32,
      text: "왼쪽의 센서가 물리량을 측정합니다. 가운데 네트워크가 그 값을 옮기고, 오른쪽 클라우드에서 학습과 추론이 이어집니다.",
      source: "preview",
    },
    {
      slide_number: 4,
      title: "용어 정의: MQTT",
      slide_type: "definition",
      estimated_seconds: 240,
      spoken_seconds: 30,
      text: "MQTT는 발행과 구독으로 기기 사이 메시지를 전달합니다. 보내는 쪽과 받는 쪽이 같은 주소만 맞으면 됩니다.",
      source: "preview",
    },
    {
      slide_number: 5,
      title: "토픽은 주소입니다",
      slide_type: "concept",
      estimated_seconds: 240,
      spoken_seconds: 26,
      text: "토픽은 메시지를 분류하는 주소입니다. 같은 토픽을 구독한 기기만 그 메시지를 받습니다.",
      source: "preview",
    },
    {
      slide_number: 6,
      title: "오늘 배운 말",
      slide_type: "summary",
      estimated_seconds: 120,
      spoken_seconds: 20,
      text: "오늘은 센서에서 추론으로 이어지는 AIoT 흐름과, 토픽으로 메시지를 나누는 MQTT를 정리했습니다.",
      source: "preview",
    },
  ];
  return {
    project_id: projectId,
    title: "AIoT와 MQTT 입문",
    slide_count: slides.length,
    total_seconds: slides.reduce((n, s) => n + s.spoken_seconds, 0),
    slides,
    writer: "preview",
    model_name: null,
  };
}

export function emptyProject(id: string, title: string | null, now: string): Project {
  return {
    id,
    title,
    presentation_status: null,
    error_message: null,
    source_file: null,
    has_analysis: false,
    source_analysis: null,
    lecture_profile: null,
    has_plan: false,
    has_slides: false,
    has_enrichment: false,
    has_prompt: false,
    has_presentation: false,
    has_video: false,
    input_mode: "source",
    presentation_provider: null,
    created_at: now,
    updated_at: now,
  };
}

export function demoProject(now: string): Project {
  const id = "preview-demo";
  return {
    ...emptyProject(id, "AIoT와 MQTT 입문", now),
    presentation_status: "planned",
    source_file: {
      filename: "aiot-mqtt-sample.md",
      extension: ".md",
      size_bytes: 4200,
      content_type: "text/markdown",
      uploaded_at: now,
    },
    has_analysis: true,
    source_analysis: SAMPLE_ANALYSIS,
    lecture_profile: sampleProfile(id, now),
    has_plan: true,
    has_slides: true,
    input_mode: "source",
  };
}
